
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
  
  app:
    build:
      context: ./app
      dockerfile: ../docker/app/Dockerfile
    container_name: app
    ports:
      - "3000:3000"
    depends_on:
      - nginx
  
  api:
    build:
      context: ./api
      dockerfile: ../docker/api/Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=products

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=products
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

